export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const REMOVE_ITEM = 'REMOVE_ITEM';
