export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_ITEM';
export const SET_CART_VISIBILITY = 'SET_CART_VISIBILITY';
export const TOGGLE_CART_VISIBILITY = 'TOGGLE_CART_VISIBILITY';
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
